"""
PDF Clinical Report Generator.

Produces a 2-page professional PDF report for trial sponsors and clinical
operations teams. Uses fpdf2 for layout. All output is clearly labelled
as educational and portfolio demonstration material.
"""

from fpdf import FPDF
from pathlib import Path
from datetime import date
from typing import Dict

PROJECT_ROOT = Path(__file__).parent.parent
REPORTS_DIR = PROJECT_ROOT / "reports"

DISCLAIMER = (
    "This report is for educational and portfolio demonstration purposes only. "
    "It does not constitute clinical advice and should not be used for patient care decisions."
)
FOOTER_LINE2 = "Generated by AI-Powered Clinical Trial Retention Intelligence System"
FOOTER_LINE3 = "Dr. Reema Mohamed Sulthan, PharmD | github.com/reemahussain-pharmd"


def _safe(text: str) -> str:
    """Replace Unicode characters not supported by Helvetica with ASCII equivalents."""
    return (
        str(text)
        .replace("–", "-")   # en dash
        .replace("—", "--")  # em dash
        .replace("→", "->")  # right arrow
        .replace("←", "<-")  # left arrow
        .replace("°", " deg")  # degree
        .replace("×", "x")   # multiplication
        .replace("’", "'")   # right single quote
        .replace("‘", "'")   # left single quote
        .replace("“", '"')   # left double quote
        .replace("”", '"')   # right double quote
        .replace("é", "e")   # e acute
        .replace("à", "a")   # a grave
        .replace("∞", "inf") # infinity
    )

TEAL = (29, 158, 117)
NAVY = (13, 27, 42)
LIGHT_GRAY = (245, 245, 245)
MID_GRAY = (180, 180, 180)
WHITE = (255, 255, 255)
RED_RISK = (200, 50, 50)
AMBER_RISK = (220, 150, 30)
GREEN_RISK = (29, 158, 117)


def _risk_colour(category: str):
    if category == "HIGH":
        return RED_RISK
    elif category == "MEDIUM":
        return AMBER_RISK
    return GREEN_RISK


class RetentionReport(FPDF):
    """Custom FPDF subclass with header/footer support."""

    def __init__(self, patient_id: str):
        super().__init__()
        self.patient_id = patient_id
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(15, 15, 15)

    def cell(self, w=0, h=0, text="", *args, **kwargs):
        return super().cell(w, h, _safe(str(text)), *args, **kwargs)

    def safe_multi_cell(self, w, h, text="", **kwargs):
        self.set_x(self.l_margin)  # always start from left margin
        if w == 0:
            w = self.epw
        return super().multi_cell(w, h, _safe(str(text)), **kwargs)

    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 18, "F")
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 12)
        self.set_xy(10, 4)
        self.cell(0, 10, "Clinical Trial Retention Intelligence Report", ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_xy(10, 10)
        self.cell(
            0, 6,
            f"Patient: {self.patient_id}  |  Date: {date.today().strftime('%d %B %Y')}  |  CONFIDENTIAL",
        )
        self.ln(10)

    def footer(self):
        self.set_y(-28)
        self.set_draw_color(*TEAL)
        self.set_line_width(0.4)
        self.line(15, self.get_y(), 195, self.get_y())
        self.ln(2)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*MID_GRAY)
        self.multi_cell(0, 4, DISCLAIMER, align="C")
        self.set_font("Helvetica", "", 7)
        self.cell(0, 4, FOOTER_LINE2, ln=True, align="C")
        self.cell(0, 4, FOOTER_LINE3, align="C")

    def section_heading(self, text: str):
        self.set_fill_color(*TEAL)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 7, f"  {text}", ln=True, fill=True)
        self.ln(2)
        self.set_text_color(30, 30, 30)

    def kv_row(self, label: str, value: str, bold_value: bool = False):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(80, 80, 80)
        self.cell(65, 6, _safe(label) + ":", ln=False)
        if bold_value:
            self.set_font("Helvetica", "B", 9)
        self.set_text_color(20, 20, 20)
        self.cell(0, 6, _safe(value), ln=True)

    def colored_risk_badge(self, category: str, pct: int):
        r, g, b = _risk_colour(category)
        self.set_fill_color(r, g, b)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 14)
        self.cell(
            50, 14,
            f"{pct}%  {category} RISK",
            border=1, ln=False, align="C", fill=True,
        )
        self.ln(16)
        self.set_text_color(20, 20, 20)


def generate_report(analysis: Dict, patient_id: str = "DEMO") -> Path:
    """
    Generate a 2-page PDF retention intelligence report.

    Args:
        analysis: Full analysis dict returned by RetentionAgent.run().
        patient_id: Patient identifier for the report header.

    Returns:
        Path to the saved PDF file.
    """
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    pdf = RetentionReport(patient_id=patient_id)
    pdf.add_page()

    # ── PAGE 1 ───────────────────────────────────────────────────────────────

    # Sub-header
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(*TEAL)
    pdf.cell(0, 8, "Dr. Reema Mohamed Sulthan, PharmD | Clinical Data Scientist | Certified AI Expert", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 5, "Clinical Data Scientist | AI-Powered Clinical Trial Retention Intelligence System", ln=True)
    pdf.ln(4)

    # Risk summary
    pdf.section_heading("Patient Risk Summary")
    risk_cat = analysis.get("risk_category", "UNKNOWN")
    risk_pct = analysis.get("risk_pct", 0)
    pdf.colored_risk_badge(risk_cat, risk_pct)

    pdf.kv_row("Patient ID", patient_id)
    pdf.kv_row("Patient Persona", analysis.get("persona", "—"))
    pdf.kv_row("Estimated Dropout Window", analysis.get("dropout_window", "—"))
    pdf.kv_row("Report Date", date.today().strftime("%d %B %Y"))
    pdf.ln(4)

    # Top risk factors
    pdf.section_heading("Top 3 Dropout Risk Factors (SHAP Analysis)")
    risk_factors = analysis.get("top3_risk_factors", [])
    if risk_factors:
        for i, (feat, shap_val, label) in enumerate(risk_factors, 1):
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(20, 20, 20)
            pdf.cell(8, 6, f"{i}.", ln=False)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(80, 6, label, ln=False)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(180, 60, 60)
            pdf.cell(0, 6, f"Risk contribution: +{shap_val:.3f}", ln=True)
            pdf.set_text_color(20, 20, 20)
    pdf.ln(3)

    # Protective factors
    pdf.section_heading("Top 3 Protective Factors")
    protective = analysis.get("top3_protective_factors", [])
    if protective:
        for i, (feat, shap_val, label) in enumerate(protective, 1):
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(8, 6, f"{i}.", ln=False)
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(80, 6, label, ln=False)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(29, 158, 117)
            pdf.cell(0, 6, f"Protective contribution: {shap_val:.3f}", ln=True)
            pdf.set_text_color(20, 20, 20)
    pdf.ln(3)

    # Supporting evidence
    pdf.section_heading("Supporting Clinical Evidence")
    evidence_list = analysis.get("evidence", [])
    printed = 0
    for item in evidence_list:
        ev = item.get("evidence")
        if ev and printed < 2:
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(0, 5, f"Re: {item['intervention']}", ln=True)
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(80, 80, 80)
            pdf.safe_multi_cell(0, 5, f"Source: {ev['source']}")
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(20, 20, 20)
            pdf.safe_multi_cell(0, 5, ev["recommendation"])
            pdf.ln(2)
            printed += 1

    # ── PAGE 2 ───────────────────────────────────────────────────────────────
    pdf.add_page()

    # Interventions table
    pdf.section_heading("Recommended Retention Interventions")
    interventions = analysis.get("interventions", [])

    # Table header
    pdf.set_fill_color(*NAVY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 8)
    col_w = [72, 35, 48, 25]
    headers = ["Intervention", "Owner", "Est. Potential Risk Reduction", "Cost"]
    for h, w in zip(headers, col_w):
        pdf.cell(w, 7, h, border=1, fill=True, ln=False, align="C")
    pdf.ln()

    pdf.set_text_color(20, 20, 20)
    for i, iv in enumerate(interventions):
        fill = i % 2 == 0
        bg = LIGHT_GRAY if fill else WHITE
        pdf.set_fill_color(*bg)
        reduction_short = iv["estimated_potential_risk_reduction"].replace(
            "Estimated Potential Risk Reduction: ", ""
        )
        row_vals = [
            iv["name"][:45],
            iv["owner"][:22],
            reduction_short,
            f"${iv['cost']:,.0f}",
        ]
        pdf.set_font("Helvetica", "", 7)
        for val, w in zip(row_vals, col_w):
            pdf.cell(w, 6, val, border=1, fill=fill, ln=False)
        pdf.ln()

    pdf.ln(4)

    # Top intervention PharmD rationale
    if interventions:
        pdf.section_heading("PharmD Rationale — Priority Intervention")
        top_iv = interventions[0]
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 6, top_iv["name"], ln=True)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(60, 60, 60)
        pdf.safe_multi_cell(0, 5, top_iv["pharmd_rationale"])
        pdf.set_text_color(20, 20, 20)
        pdf.ln(3)

    # What-If preview
    top_scenarios = analysis.get("top_scenarios", [])
    if top_scenarios:
        pdf.section_heading("What-If Scenario Preview")
        for sc in top_scenarios:
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(0, 5, sc["label"], ln=True)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(60, 60, 60)
            pdf.safe_multi_cell(0, 5, sc["interpretation"])
            pdf.set_text_color(20, 20, 20)
            pdf.ln(2)

    # Business impact
    impact = analysis.get("business_impact", {})
    if impact:
        pdf.section_heading("Business Impact (Modelled Estimates)")
        pdf.set_font("Helvetica", "", 9)
        col_a = 90
        col_b = 0

        def impact_row(label, value, teal=False):
            if teal:
                pdf.set_text_color(*TEAL)
                pdf.set_font("Helvetica", "B", 9)
            else:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(20, 20, 20)
            pdf.cell(col_a, 6, label, ln=False)
            pdf.cell(col_b, 6, value, ln=True)
            pdf.set_text_color(20, 20, 20)

        impact_row("Patient Replacement Cost (if dropped out):",
                   f"${impact.get('replacement_cost_avoided', 0):,.0f}")
        impact_row("Total Intervention Cost:",
                   f"${impact.get('intervention_total_cost', 0):,.0f}")
        impact_row("Estimated Net Savings (modelled):",
                   f"${impact.get('net_savings', 0):,.0f}", teal=True)
        roi = impact.get("roi_ratio", 0)
        roi_str = f"{roi:.1f}×" if roi != float("inf") else "∞"
        impact_row("Return on Investment (modelled):", roi_str, teal=True)

    # Save
    out_path = REPORTS_DIR / f"retention_report_{patient_id}.pdf"
    pdf.output(str(out_path))
    return out_path


def generate_sample_report() -> Path:
    """
    Generate a sample PDF report using demo patient data.

    Returns:
        Path to the saved sample PDF.
    """
    sample_analysis = {
        "risk_score": 0.74,
        "risk_category": "HIGH",
        "risk_pct": 74,
        "dropout_window": "Weeks 4–8 (Early Treatment Phase)",
        "persona": "Long-Distance Rural Participant",
        "persona_description": "Participant residing >80 km from site without transportation access.",
        "top3_risk_factors": [
            ("side_effect_severity_at_week2", 0.28, "Week 2 Side Effect Severity"),
            ("logistic_friction_score", 0.21, "Logistic Friction Score"),
            ("distance_from_site_km", 0.18, "Distance from Trial Site"),
        ],
        "top3_protective_factors": [
            ("investigator_experience_years", -0.09, "Investigator Experience (Years)"),
            ("insurance_status_insured", -0.05, "Insurance: Insured"),
            ("prior_trial_participation", -0.04, "Prior Trial Participation"),
        ],
        "interventions": [
            {
                "name": "Transportation Reimbursement Program",
                "owner": "Site Coordinator",
                "estimated_potential_risk_reduction": "Estimated Potential Risk Reduction: Moderate",
                "cost": 300.0,
                "pharmd_rationale": (
                    "Geographic barrier is a primary non-clinical dropout cause. "
                    "Reimbursing transport removes practical friction without protocol changes. "
                    "(Reference: FDA Guidance for Industry: Patient Retention in Clinical Trials, 2012)"
                ),
            },
            {
                "name": "Dedicated Safety Monitoring Call (weekly)",
                "owner": "Principal Investigator + Study Nurse",
                "estimated_potential_risk_reduction": "Estimated Potential Risk Reduction: High",
                "cost": 150.0,
                "pharmd_rationale": (
                    "Early AE severity at week 2 is associated with discontinuation. "
                    "Proactive pharmacovigilance contact allows early AE management."
                ),
            },
        ],
        "evidence": [
            {
                "intervention": "Transportation Reimbursement Program",
                "evidence": {
                    "source": "FDA (2012). Guidance for Industry: Patient Retention in Clinical Trials.",
                    "evidence": "Logistical barriers including transportation were identified as modifiable factors affecting patient retention.",
                    "recommendation": "Trial sponsors should consider transportation reimbursement as a standard retention strategy.",
                },
            }
        ],
        "top_scenarios": [
            {
                "label": "Add transportation support",
                "interpretation": "Adding transportation support may reduce dropout risk from 74% to approximately 55% (estimated reduction: 19.0 percentage points).",
                "original_risk": 0.74,
                "new_risk": 0.55,
                "risk_reduction_pct": 19.0,
            }
        ],
        "business_impact": {
            "replacement_cost_avoided": 18000,
            "intervention_total_cost": 450,
            "net_savings": 17550,
            "roi_ratio": 39.0,
        },
    }
    return generate_report(sample_analysis, "SAMPLE")


if __name__ == "__main__":
    path = generate_sample_report()
    print(f"Sample report saved → {path}")
